야믈파일 DB는 로컬DB입니다.
dodeca05/wolMgr pull request #1
Opened 2023-03-23 04:25 UTC by yu-teacher

그래들 swagger 추가 했읍니다.
config 패키지 추가 했습니다
test 컨트롤러 만들어서 추가 했습니다.

2023-03-23 15:51 UTC, dodeca05 commented on src/main/java/com/pro/WOLmgr/controller/TestController.java
> +    @GetMapping("/test")
테스트 코멘트 입니다.

2023-03-23 15:51 UTC, dodeca05 commented on src/main/resources/application.yml
> +        password: "0000"
jdbc도 추가해 놨네??

2023-03-23 15:52 UTC, dodeca05 requested changes
코멘트 확인할때 까지 거부

2023-03-23 15:54 UTC, dodeca05 commented
pr 제목이 맘에 안듬 ㅋㅋㅋ

2023-03-24 02:34 UTC, yu-teacher commented on src/main/java/com/pro/WOLmgr/controller/TestController.java
> +    @GetMapping("/test")
그렇읍니까?

2023-03-24 02:34 UTC, yu-teacher commented on src/main/resources/application.yml
> +        password: "0000"
우아한 테크코스 아직 안열린거 같읍니다 ㅠㅠㅠ

2023-03-24 02:39 UTC, dodeca05 approved these changes
승인합니다

2023-03-24 02:40 UTC, merged