회원가입, 로그인 기능입니다.
dodeca05/wolMgr pull request #11
Opened 2023-04-11 04:07 UTC by yu-teacher

# Pr 종류
- [ ] task (개발)
- [ ] bugfix (버그 수정)
- [ ] etc (그 외)

# 무엇이 문제인가요? (What)
로그인 기능이 없고 회원가입 기능이 없었습니다. 

# 어떻게 해결하고 구현했나요? (How)
토큰을 사용하여 로그인 기능을 만들었고 로그인을 하면 토큰을 발행하여 클라이언트의 로컬스토리지에 저장했습니다.
이메일 인증 기능을 사용하여 이메일의 유효성을 증가시켰습니다.

# 테스트 했나요?
- [ ] Local Test (본인 pc 에서 테스트)
- [ ] include Test Code (테스트 코드 포함)

2023-04-12 22:54 UTC, dodeca05 reviewed
프론트 리뷰는 생략했습니다

2023-04-12 22:54 UTC, dodeca05 commented on src/main/java/com/pro/WOLmgr/Jwt/JwtAuthenticationFilter.java
> +            throw new RuntimeException(e);
상단에 throws를 썼으니 이것도 위에 밀어 넣는 것이 어떤가요?

2023-04-12 22:54 UTC, dodeca05 commented on src/main/java/com/pro/WOLmgr/Jwt/JwtAuthenticationFilter.java
> +                .withExpiresAt(new Date(System.currentTimeMillis()+1000*60*10)) // 만료시간 밀리초단위
만료시간이 10분이면 너무 짧지 않나요?

2023-04-12 22:54 UTC, dodeca05 commented on src/main/java/com/pro/WOLmgr/Jwt/JwtAuthenticationFilter.java
> +                .withClaim("userNumber",principalDetails.getUser().getUserNumber()) // 유저 넘버
정보를 넣는 건가요? 암호화를 위한 키 인가요?(진짜 모름)

2023-04-12 22:54 UTC, dodeca05 commented on src/main/java/com/pro/WOLmgr/configuration/CorsConfig.java
> +    }
CORS는 보안관련 정책입니다
지정한 곳으로 부터만 통신하겠다는 것인데 모든 것을 열어두면 이 토이 프로젝트는 괜찮지만 실제 운영 서버에 side effects 가 생길 것 같습니다.
좀 더 공부해볼 필요가 있을 것 같습니다 (나도 모름)

2023-04-12 22:54 UTC, dodeca05 commented on src/main/java/com/pro/WOLmgr/configuration/EmailConfiguration.java
> +
구글 계정에서 smtp를 사용하는 설정이 따로 있는 것으로 알고 있습니다만 해당 설정에서 MAC 주소 등 개인정보를 요구 할 것 입니다.
각자 SMTP를 설정 할 수 는 있지만 이는 다소 번거롭고 모든 개발자가 다루는 영역이 아니기 때문에 smtp가 환경 변수로 등록되어 있지 않으면 smtp기능이 비활성화 되는 코드를 넣는 건 어떨까요?

해당 코드가 잘 못 되었다는건 아니고 저의 제안 입니다.

2023-04-12 22:54 UTC, dodeca05 commented on src/main/java/com/pro/WOLmgr/configuration/SecurityConfiguration.java
> +        // 세션 생성 정책 설정 (무상태 세션)
보안 관련해서 항상 side effects 를 조사해둡시다.

2023-04-12 22:54 UTC, dodeca05 commented on src/main/java/com/pro/WOLmgr/controller/UserController.java
> +
위의 Get mapping 이 이해가 잘 안갑니다

2023-04-12 22:54 UTC, dodeca05 commented on src/main/java/com/pro/WOLmgr/dto/UserDTO.java
> +    }
UserDTO를 두개 만듭시다
해당 DTO 사용영역은 정확히 확인 및 파악을 못했지만 아마 회원가입 영역에 사용할 것으로 생각됩니다.
로직과 관련이 없다면 비밀번호를 포함한 DTO를 쓰는건 보안 이슈로 좋지 못합니다.
UserInfoDTO, UserPrivacyDTO 두개를 만들어 회원 조회, 권한 조회에는 비밀번호가 필요없는 UserInfoDTO를 쓰고 회원가입이나 로그인에 사용할때는 UserPrivacyDTO를 쓰는 쪽으로 수정합시다

2023-04-12 22:54 UTC, dodeca05 commented on src/main/java/com/pro/WOLmgr/service/MailService.java
> +        mailSend(setFrom, toMail, title, msgg);
별도의 html 파일로 관리했으면 좋겠습니다
파일을 string으로 가져와서 replace만 하도록 변경합시다

2023-04-12 22:54 UTC, dodeca05 commented on src/main/java/com/pro/WOLmgr/service/PrincipalDetailsService.java
> +}
정확한 이해를 못했습니다 설명좀 ㅎㅎ;

2023-04-12 22:54 UTC, dodeca05 commented on src/main/java/com/pro/WOLmgr/service/UserService.java
> +}
이메일 중복 확인이 있었던거 같은데

2023-04-12 22:54 UTC, dodeca05 commented on src/main/java/com/pro/WOLmgr/util/PrincipalDetails.java
> +}
모르는 내용 ㅠ

2023-04-13 00:48 UTC, yu-teacher commented on src/main/java/com/pro/WOLmgr/util/PrincipalDetails.java
> +}
제가 아는바로는 회원의 활성화 여부라는 것이 아마 유령회원과 실사용 회원등을 나누는 것으로 알고 있습니다. 그래서 모든 회원을 true로 반환하도록 하였습니다.

2023-04-13 00:49 UTC, yu-teacher commented on src/main/java/com/pro/WOLmgr/service/UserService.java
> +}
이메일 중복확인 로직은 이거 하나입니다. 어떤거랑 겹치는지 주석 달아주시면 감사하겠습니다.

2023-04-13 00:50 UTC, yu-teacher commented on src/main/java/com/pro/WOLmgr/service/MailService.java
> +        mailSend(setFrom, toMail, title, msgg);
그렇게 사용해본적이 없어서 그런데 별도 html로 주게 된다면 변수를 유동적으로 줄 수 있나요?

2023-04-13 01:10 UTC, yu-teacher commented on src/main/java/com/pro/WOLmgr/dto/UserDTO.java
> +    }
패스워드 인코더를 사용하였기 때문에 보안상 이슈가 크게 없을 것이라고 생각했습니다. 
수정하겠습니다.
이 로직은 서비스제작할 때 유저의 정보가 반환 될 필요가 있을 때 사용하려고 만들어 두었습니다.

2023-04-13 01:10 UTC, yu-teacher commented on src/main/java/com/pro/WOLmgr/controller/UserController.java
> +
최초 루트 경로로 이동했을 때 로그인 창으로 이동하도록 한 것입니다.

2023-04-13 01:13 UTC, yu-teacher commented on src/main/java/com/pro/WOLmgr/configuration/EmailConfiguration.java
> +
저는 공용으로 사용하기 위해서 WOLMgr계정을 만들었습니다. 그걸 공유해드리는 것을 깜박했네요.
회원가입을 하기 위해서는 위 로직이 필수적으로 사용되어야 하니 그걸 공유해드리는 것이 나을 것 같은데 괜찮을까요?

2023-04-13 01:14 UTC, yu-teacher commented on src/main/java/com/pro/WOLmgr/Jwt/JwtAuthenticationFilter.java
> +            throw new RuntimeException(e);
수정해보겠습니다.

2023-04-13 01:19 UTC, yu-teacher commented on src/main/java/com/pro/WOLmgr/Jwt/JwtAuthenticationFilter.java
> +                .withExpiresAt(new Date(System.currentTimeMillis()+1000*60*10)) // 만료시간 밀리초단위
사실 5분에서 3분으로 조금 더 짧게 가져가는 것이 안전하다고 생각했습니다. 저희 서비스의 크기가 얼마나 커질지는 모르겠으나. 일반적으로 한두개의 서비스를 사용한 뒤 오래 사용할 것 같지가 않아서 짧게 잡았습니다. 

우리의 로그인 방식은 클라이언트에 토큰을 쏴서 클라이언트의 로컬스토리지에 토큰을 저장해두고 페이지 로드마다 서버에서 확인하도록 조치하였습니다. 만약 그럴 일은 없겠지만 제가 아닌 다른 사용자가 크롬을 켤 수 있다면 언제든지 접근이 가능해지는 것 입니다. 따라서 짧게 가져가는 것이 안전하다고 생각했습니다.

2023-04-13 01:24 UTC, yu-teacher commented on src/main/java/com/pro/WOLmgr/Jwt/JwtAuthenticationFilter.java
> +                .withClaim("userNumber",principalDetails.getUser().getUserNumber()) // 유저 넘버
네 정보를 넣는겁니다. 

[https://jwt.io/](url)

링크 첨부 하겠습니다. 토큰을 발행해 보시고 여기 붙여넣기 하시면 토큰이 읽힐겁니다.

2023-04-13 01:25 UTC, yu-teacher commented on src/main/java/com/pro/WOLmgr/configuration/CorsConfig.java
> +    }
저도 잘 모르는 부분이라서 우리 프로젝트가 만약 확장된다면 이쪽 코드를 수정하여 접근을 제한하는 방식을 사용해야 하지 않을까 싶습니다.

2023-04-13 01:29 UTC, yu-teacher commented on src/main/java/com/pro/WOLmgr/service/PrincipalDetailsService.java
> +}
src/main/java/com/pro/WOLmgr/util/PrincipalDetails.java 을 보시면 회원의 데이터를 스프링 시큐리티에서 사용할 수 있도록 하는 것입니다.

2023-04-13 01:31 UTC, yu-teacher commented
> 프론트 리뷰는 생략했습니다

자바 스크립트 코드는 보시는게 좀 낫지 않을까 싶습니다.

2023-04-13 02:52 UTC, yu-teacher commented on src/main/java/com/pro/WOLmgr/Jwt/JwtAuthenticationFilter.java
> +            throw new RuntimeException(e);
자바 롬복의 @SneakyThrows 어노테이션을 사용하면 모든 예외처리를 손쉽게 할 수 있습니다. 제 생각에 오류이름의 명시가 필요 없거나 별도의 예외처리를 하지 않아도 되는상황에서 가독성 향상을 위해서 이 어노테이션을 사용하는게 어떨까 생각합니다. 이하는 ChatGPT형님의 설명입니다.

'@SneakyThrows' 어노테이션은 메서드나 생성자의 선언부에 사용되며, 해당 메서드나 생성자가 발생할 수 있는 예외를 자동으로 처리해줍니다. 예를 들어, 일반적으로 예외를 처리하는 try-catch 블록을 사용해야 하는 상황에서 '@SneakyThrows' 어노테이션을 사용하면, 컴파일러가 자동으로 try-catch 블록을 생성해주기 때문에 개발자가 직접 예외를 처리하는 코드를 작성하지 않아도 됩니다.

예를 들어, 다음과 같이 '@SneakyThrows' 어노테이션을 사용하여 예외를 처리할 수 있습니다:

```
import lombok.SneakyThrows;

public class Example {
    @SneakyThrows
    public void doSomething() {
        // 예외를 발생시킬 수 있는 코드
    }
}
```
위의 예제에서 '@SneakyThrows' 어노테이션이 선언된 'doSomething()' 메서드에서 예외가 발생하면, 롬복이 자동으로 예외를 처리해주기 때문에 개발자가 직접 예외 처리 코드를 작성하지 않아도 됩니다. 다만, '@SneakyThrows' 어노테이션은 예외를 무시하고 넘어가는 것이기 때문에, 예외를 처리하는 방식에 주의해야 합니다. 잘못된 사용은 디버깅이 어려워질 수 있고, 예외를 무시하고 넘어가는 부작용이 발생할 수 있습니다. 따라서, 사용 시 주의해서 사용해야 합니다.

2023-04-14 08:14 UTC, dodeca05 commented on src/main/java/com/pro/WOLmgr/Jwt/JwtAuthenticationFilter.java
> +            throw new RuntimeException(e);
이슈에서 쓴 것처럼 로그가 안남아 쓰지 않는게 좋을 것 같습니다.
참고로 throws가 try catch보다 좋다 이런 부분으로 말한건 아니고 특별한 이유가 없다면 예외 처리시 한 메소드 안에서 일관성을 지켰으면 좋겠습니다.

2023-04-14 08:15 UTC, dodeca05 commented on src/main/java/com/pro/WOLmgr/Jwt/JwtAuthenticationFilter.java
> +                .withExpiresAt(new Date(System.currentTimeMillis()+1000*60*10)) // 만료시간 밀리초단위
웹으로 접근할때 말고 일단 api도 호출 할 수 있습니다. 일단 24시간으로 바꿨으면 좋겠습니다

2023-04-14 08:16 UTC, dodeca05 commented on src/main/java/com/pro/WOLmgr/service/MailService.java
> +        mailSend(setFrom, toMail, title, msgg);
변수 부분만 replace 하도록 합시다

2023-04-14 08:42 UTC, yu-teacher commented on src/main/java/com/pro/WOLmgr/Jwt/JwtAuthenticationFilter.java
> +            throw new RuntimeException(e);
수정완료

2023-04-14 08:43 UTC, yu-teacher commented on src/main/java/com/pro/WOLmgr/dto/UserDTO.java
> +    }
수정완료

2023-04-14 08:43 UTC, yu-teacher commented on src/main/java/com/pro/WOLmgr/Jwt/JwtAuthenticationFilter.java
> +                .withExpiresAt(new Date(System.currentTimeMillis()+1000*60*10)) // 만료시간 밀리초단위
수정완료

2023-04-14 12:00 UTC, dodeca05 commented on src/main/java/com/pro/WOLmgr/service/UserService.java
> +}
잘못 알았던 것 같습니다

2023-04-14 13:18 UTC, yu-teacher commented on src/main/java/com/pro/WOLmgr/service/MailService.java
> +        mailSend(setFrom, toMail, title, msgg);
수정완료

2023-04-15 16:45 UTC, yu-teacher commented on src/main/java/com/pro/WOLmgr/configuration/EmailConfiguration.java
> +
수정완료 하였습니다.

2023-04-16 11:47 UTC, dodeca05 requested changes
코드 전체적으로 문제 없어 보입니다. 오타와 자잘한 규칙정도 수정해 주세요

2023-04-16 11:47 UTC, dodeca05 commented on src/main/resources/static/js/isEmail.js
> +        if (result.result === 'noContain') {
REST API 규직에 위반하는 api 이름

2023-04-16 11:47 UTC, dodeca05 commented on src/main/resources/static/js/isEmail.js
> +    ajaxForm('POST', '/emailCheck', data, function (result) {
REST API 규직에 위반하는 api 이름

2023-04-16 11:47 UTC, dodeca05 commented on src/main/java/com/pro/WOLmgr/controller/CheckController.java
> +    @GetMapping("/checkEamil")
Email 오타 발견

2023-04-16 13:22 UTC, dodeca05 approved these changes
승인합니다. 고생하셨습니다.
다음엔 pr을 좀 더 작게 쪼개서 올려주세요

2023-04-16 13:22 UTC, yu-teacher commented
> 승인합니다. 고생하셨습니다. 다음엔 pr을 좀 더 작게 쪼개서 올려주세요

선생님이 보느라 고생 많았죠 다음부턴 조심하겠습니다.

2023-04-16 13:22 UTC, merged