디바이스 등록 및 삭제입니다.
dodeca05/wolMgr pull request #16
Opened 2023-04-20 06:31 UTC by yu-teacher

# Pr 종류
- [ ] task (개발)
- [ ] bugfix (버그 수정)
- [ ] etc (그 외)

# 무엇이 문제인가요? (What)
디바이스 등록 기능과 삭제 기능이 없었습니다.

# 어떻게 해결하고 구현했나요? (How)
디바이스를 등록, 삭제할 수 있게 만들었습니다. 그리고 디바이스 이름으로 한글이 들어왔을 떄 런타임 에러를 출력하고 로직이 멈추도록 설계했읍니다.^^

# 테스트 했나요?
- [ ] Local Test (본인 pc 에서 테스트)
- [ ] include Test Code (테스트 코드 포함)

2023-04-20 10:46 UTC, dodeca05 requested changes
비교적 사소한 부분만 수정하면 될 것 같습니다

2023-04-20 10:46 UTC, dodeca05 commented on src/main/java/com/pro/WOLmgr/entity/Device.java
> +public class Device {
DeviceEntity 가 더 좋은 이름 같습니다

2023-04-20 10:46 UTC, dodeca05 commented on src/main/java/com/pro/WOLmgr/controller/WolServiceController.java
> +        if(!deviceInfoDTO.getDeviceName().matches("[a-zA-Z]+")){
숫자는 포함했으면 좋겠습니다 ㅎㅎ;;;;

2023-04-20 10:46 UTC, dodeca05 commented on src/main/java/com/pro/WOLmgr/controller/WolServiceController.java
> +        String result = deviceService.register(deviceInfoDTO)? "suckSex!":"fuck!";
면접관이 이 코드를 본다면 정말 좋아할것 같네요

2023-04-20 10:46 UTC, dodeca05 commented on src/main/java/com/pro/WOLmgr/controller/WolServiceController.java
>      public String computerInfo(@RequestBody DeviceInfoDTO deviceInfoDTO){
REST API는 생성한 결과를 돌려주는 것이 원칙입니다.

2023-04-20 10:46 UTC, dodeca05 commented on src/main/java/com/pro/WOLmgr/controller/WolServiceController.java
> +            throw new RuntimeException("영어를 제외한 나머지 멈춰!");
REST API 규칙에 위배 될 수 있습니다.
일반적으로 예외를 던지면 http status값이 500으로 알고 있습니다
500은 사용자는 문제 없는데 우리 내부적으로 문제가 있어 라는 뜻 입니다.
영어를 검사하는 건 우리가 사용자에게 요구하는 것 이므로 사용자가 영어가 아닌 다른 언어를 적었을 때 사용자가 잘 못 한 것으로 해야 됩니다. 이때 http status code는 400번대 입니다. 적절한 에러 코드를 선정해서 고르면 좋겠습니다.

2023-04-22 09:18 UTC, yu-teacher commented
면접관이 보면 좋아할 코드 포함 코드 수정 완료했습니다. 검토 부탁드립니다.

2023-04-23 08:15 UTC, dodeca05 approved these changes
중요한 로직은 문제 없으므로 일단 승인합니다.
제가 남긴 의견을 일단 제고해주세요

2023-04-23 08:15 UTC, dodeca05 commented on src/main/java/com/pro/WOLmgr/controller/WolServiceController.java
> +    @PutMapping("/Packet/{packet}")
REST API 규칙에 의해 소문자를 사용합시다

2023-04-23 08:15 UTC, dodeca05 commented on src/main/java/com/pro/WOLmgr/controller/WolServiceController.java
>      }
등록 관련 로직은 컨트롤러가 아니고 서비스에 들어가야 되지 않을까요? 컨트롤러는 서비스 연결 역활만 하고 서비스의 반환 결과에 따라 어떤 대답과 메세지를 줄지 결정하는 역할만 해야 된다고 생각합니다.

어쩔 수 없는 상황이나 너무 간단한 로직은 컨트롤러에 올리기도 하지만 저 같으면 값을 체크하는 부분을 deviceService.register에 넣을 것 같습니다.

2023-04-23 08:15 UTC, dodeca05 commented on src/main/java/com/pro/WOLmgr/dto/DeviceResponseDTO.java
> +
굳이 static일 필요가 있을까요?

2023-04-23 08:18 UTC, dodeca05 commented on src/main/java/com/pro/WOLmgr/service/DeviceService.java
> +        return toDTO(deviceRepository.save(toEntity(deviceRequestDTO)));
import 부분에 명시되어 있고 위에 남긴 의견과 같은 맥락입니다만
가독성 측면에서 static을 제거하여 어떤 DTO로 변환되는지 명시할 필요가 있지 않을까요?

2023-04-23 08:19 UTC, dodeca05 commented on src/main/java/com/pro/WOLmgr/service/DeviceService.java
> +        return toDTO(deviceRepository.save(toEntity(deviceRequestDTO)));
지금은 간단한 코드 지만 서비스 로직이 복잡하면 DTO로 변환될때 어떤 DTO인지 찾느라 가독성이 저하될 것 입니다.

2023-04-23 08:23 UTC, bae-wongang commented on src/main/java/com/pro/WOLmgr/controller/WolServiceController.java
> +    public ResponseEntity<?> computerInfo(@RequestBody DeviceRequestDTO deviceRequestDTO){
public ResponseEntity<?> computerInfo(@RequestBody DeviceRequestDTO deviceRequestDTO){

에서 computerInfo 부분을 deviceInfo 라던가 다른 명칭과 통일시키는것은 어떨까요?

2023-04-23 08:27 UTC, bae-wongang approved these changes
전체적으로 문제는 없는거같아서 우선 승인합니다.

2023-04-23 13:58 UTC, yu-teacher commented on src/main/java/com/pro/WOLmgr/service/DeviceService.java
> +        return toDTO(deviceRepository.save(toEntity(deviceRequestDTO)));
초기에 설계에 들어올 때와 반환될 때 같은 클래스가 사용되어 그렇게 했습니다. 수정하겠습니다,

2023-04-23 13:58 UTC, yu-teacher commented on src/main/java/com/pro/WOLmgr/controller/WolServiceController.java
> +    public ResponseEntity<?> computerInfo(@RequestBody DeviceRequestDTO deviceRequestDTO){
네 네이밍을 수정할 필요가 있겠네요 감사합니다.

2023-04-23 14:01 UTC, yu-teacher commented on src/main/java/com/pro/WOLmgr/controller/WolServiceController.java
>      }
deviceService.register의 반환타입이 현재 DeviceResponseDTO인데 저 로직을 안에 집어 넣는다면 반환을 제네릭으로 해야 해서 반환타입이 모호해지는 문제가 발생할 수 있다고 생각했습니다.

2023-04-23 14:19 UTC, yu-teacher commented
다시 검토 부탁드려염 ㅠㅠ 바꾸니까 안되네

2023-04-24 01:14 UTC, merged