WOL packet 보내기
dodeca05/wolMgr pull request #5
Opened 2023-04-01 04:49 UTC by dodeca05

# Pr 종류
- [x] task (개발)
- [ ] bugfix (버그 수정)
- [ ] etc (그 외)

# 무엇이 문제인가요? (What)
wol을 패캣을 보내야 합니다.
# 어떻게 해결하고 구현했나요? (How)
targetIP와 mac 주소를 받고 이를 기반으로 magic packet을 만들어서 보냅니다.
broadcast 보내는 것도 간단하게 추가합니다.

추후 관련 entity를 작성해야 합니다.
# 테스트 했나요?
- [x] Local Test (본인 pc 에서 테스트)
- [ ] include Test Code (테스트 코드 포함)

2023-04-01 16:01 UTC, yu-teacher commented
Swagger를 사용하여 api를 시험해 보셨을 텐데 혹시 403오류가 나왔는지 궁금합니다.

2023-04-01 22:48 UTC, dodeca05 commented
> Swagger를 사용하여 api를 시험해 보셨을 텐데 혹시 403오류가 나왔는지 궁금합니다.

안나왔습니다.
다만 먼저 로그인 후 Swagger를 켰습니더

2023-04-02 01:17 UTC, yu-teacher commented
그럼 200이 나왔다는 겁니까?

2023-04-02 01:19 UTC, dodeca05 commented
넹

2023-04-02 01:27 UTC, yu-teacher requested changes
아따 성님 1따봉 드린당깨요

2023-04-02 01:37 UTC, yu-teacher approved these changes
ㅎㅎ... ㅋㅋ;; ㅈㅅ!!

2023-04-02 08:10 UTC, merged