핑보내세 health check 하기
dodeca05/wolMgr pull request #8
Opened 2023-04-07 13:02 UTC by bae-wongang

# Pr 종류
- [x] task (개발)
- [ ] bugfix (버그 수정)
- [ ] etc (그 외)

# 무엇이 문제인가요? (What)
   핑을 보내 포트가 제대로 살아있나 확인해야합니다.

# 어떻게 해결하고 구현했나요? (How)
InetAddress.getByName(ip 주소); : 서버 아이피 주소를 지정합니다.
 isReachable : 타임아웃 체크로 해당 서버에서 응답이 있을 경우 true 반환, 응답이 없을 경우 false 반환합니다. 

# 테스트 했나요?
- [x] Local Test (본인 pc 에서 테스트)
- [ ] include Test Code (테스트 코드 포함)

2023-04-07 13:15 UTC, dodeca05 requested changes
팀원들이 이 구현 분야에 대해 잘 모르므로 주석도 있으면 좋겠습니다

2023-04-07 13:15 UTC, dodeca05 commented on src/main/java/com/pro/WOLmgr/WolMgrHealthCheck.java
테스트 용 코드는 merge 하지마세요

2023-04-07 13:15 UTC, dodeca05 commented on src/main/java/com/pro/WOLmgr/service/HealthCheckService.java
> +    public void healthCheck() {
테스트 용 코드는 merge하지마세요

2023-04-07 13:15 UTC, dodeca05 commented on src/main/java/com/pro/WOLmgr/service/HealthCheckService.java
> +                System.out.println("Success");
Spring에서 Log를 남길 필요가 있다면 Log를 쓰세요

2023-04-07 13:15 UTC, dodeca05 commented on src/main/java/com/pro/WOLmgr/service/HealthCheckService.java
> +    public void healthCheck(String ip) {
PR설명과 다른내용의 코드 입니다.
성공 실패를 true false로 반환한다고 설명되는데 코드는 전혀 그렇지 않습니다

2023-04-07 13:15 UTC, dodeca05 commented on src/main/java/com/pro/WOLmgr/service/HealthCheckService.java
> +                System.out.println("Success");
Log내용도 너무 부실합니다. 성공했다면 어떤걸 성공했는지 남겨야 합니다

2023-04-07 13:23 UTC, dodeca05 commented on src/main/java/com/pro/WOLmgr/service/HealthCheckService.java
> +            inetAddress= InetAddress.getByName(ip);
DNS를 Ip로 변환하는 코드 같는데 필요성이 없어보입니다.

2023-04-07 15:08 UTC, yu-teacher commented on src/main/java/com/pro/WOLmgr/WolMgrHealthCheck.java
> +    }
main메서드는 하나만 있어야 하는 걸로 알고 있습니다.

2023-04-07 15:08 UTC, yu-teacher commented on src/main/java/com/pro/WOLmgr/service/HealthCheckService.java
> +                System.out.println("Success");
@Log4j2 사용하시면 좋을 것 같습니다.

2023-04-13 16:05 UTC, bae-wongang commented on src/main/java/com/pro/WOLmgr/WolMgrHealthCheck.java
테스트용 코드 삭제완료

2023-04-13 16:05 UTC, bae-wongang commented on src/main/java/com/pro/WOLmgr/service/HealthCheckService.java
> +    public void healthCheck() {
테스트 코드 삭제 완료

2023-04-13 16:05 UTC, bae-wongang commented on src/main/java/com/pro/WOLmgr/service/HealthCheckService.java
> +                System.out.println("Success");
log 로 변경 ,  내용 수정

2023-04-13 16:06 UTC, bae-wongang commented on src/main/java/com/pro/WOLmgr/service/HealthCheckService.java
> +    public void healthCheck(String ip) {
boolean 타입으로 변경해서 반환 받게 수정완료

2023-04-13 16:07 UTC, bae-wongang commented on src/main/java/com/pro/WOLmgr/service/HealthCheckService.java
> +            inetAddress= InetAddress.getByName(ip);
ip, dns가 들어올때 유효한 ip나 ,dns인지 확인용도로 사용예정

2023-04-13 16:07 UTC, bae-wongang commented on src/main/java/com/pro/WOLmgr/WolMgrHealthCheck.java
> +    }
삭제 완료

2023-04-14 08:11 UTC, dodeca05 requested changes
log 부분만 해결 하면 될 것 같습니다

2023-04-14 08:11 UTC, dodeca05 commented on src/main/java/com/pro/WOLmgr/service/HealthCheckService.java
> +                log.info("ping test fail");
info가 아니고 error가 더 어울릴 것 같습니다

2023-04-14 08:11 UTC, dodeca05 commented on src/main/java/com/pro/WOLmgr/service/HealthCheckService.java
> +            e.printStackTrace();
log.error를 사용해주세요

2023-04-14 08:38 UTC, bae-wongang commented on src/main/java/com/pro/WOLmgr/service/HealthCheckService.java
> +                log.info("ping test fail");
저희가 진행하는 프로젝트가 핑테스트가 실패했을경우 컴퓨터를 킬수있는 기능이 들어가야하므로 info가 맞지 않나싶습니다. 
로그의 내용은 변경할만한게 있으면 수정하겠습니다.

2023-04-14 11:58 UTC, dodeca05 commented on src/main/java/com/pro/WOLmgr/service/HealthCheckService.java
> +                log.info("ping test fail");
그 쪽 의견이 맞는 것 같습니다. 다만 로그에 어떤 ip로 보냈는지 기록 하도록 수정해 주세요

2023-04-17 15:49 UTC, dodeca05 approved these changes
승인합니다

2023-04-17 16:11 UTC, merged